### PR TITLE
Feature/proof read fixes

### PR DESCRIPTION
**Pull request by jeffreycwitt**

### CODE REVIEW

**Comment by jeffreycwitt** [comment]
Michael, I did something weird here when accepting other pull requests. We might need to skype to resolve this. There are not conflicts, but so I don't think I've lost anything, but I think I've polluted the git history

**Comment by jeffreycwitt** [comment]
The last commit 8fc169f is the one that has the proof reading changes. 8fc169f

**Comment by stenskjaer** [comment]
Okay, we will look at this. I'm on my way to bed, so I can't really do it now. But it looks like you submitted the merge to master in stead of develop? It should be possible to find a solution.

**Comment by stenskjaer** [comment]
How about just rejecting this PR and create a new with the commit a new one to develop?

**Pull request closed without merging**
